version: '3.4'

services:
  app:
    image: node:11.10.1-alpine
    command: npm run start-js
    volumes:
      - './:/app'
    working_dir: /app
    ports:
      - "3010:3000"
    stdin_open: true
    tty: true
