version: '3.4'

services:
  app:
    image: node:16.8.0-alpine3.11
    command: yarn run start-js
    user: node
    volumes:
      - './:/app'
    working_dir: /app
    ports:
      - "3010:3000"
    stdin_open: true
    tty: true
